spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    #url: jdbc:mysql://localhost:3306/program?useUnicode=true&characterEncoding=UTF8
    url: jdbc:mysql://119.23.232.221:3306/program?useUnicode=true&characterEncoding=UTF8
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
   mapperLocations: classpath:mapper/*.xml
   typeAliasesPackage: com.cailanzi.pojo
   mapUnderscoreToCamelCase: true

logging:
  level:
    com:
      cailanzi: debug
  file: myLogs/log
server:
  port: 8090


