spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://119.23.232.221:3306/program?useUnicode=true&characterEncoding=UTF8
    username: root
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 119.23.232.221
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis:
   mapperLocations: classpath:mapper/*.xml
   typeAliasesPackage: com.cailanzi.pojo
   mapUnderscoreToCamelCase: true

logging:
  level:
    com:
      cailanzi: debug
  file: myLogs/log
server:
  port: 8090
